# Generated by Django 4.0.4 on 2022-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=100, null=True)),
                ('note', models.BooleanField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
            ],
            options={
                'unique_together': {('url', 'num')},
            },
        ),
    ]
